### ISSUE TITLE
failure is deprecated

### ISSUE THREAD

**Issue by aspenluxxxy** [rust-starter/rust-starter#36]
from failure's readme:

> **Notice**: `failure` is deprecated. If you liked `failure`'s API, consider using:
> - [Anyhow](https://github.com/dtolnay/anyhow) is a good replacement for `failure::Error`.
> - [thiserror](https://github.com/dtolnay/thiserror) is a good, near drop-in replacement for `#[derive(Fail)]`.

**Comment by omarabid** [comment]
@aspenluxxxy Check the documentation. There is a "newError" branch for anyhow and thiserror.
