### ISSUE TITLE
Does not build on Windows

### ISSUE THREAD

**Issue by gregorybleiker** [rust-starter/rust-starter#40]
### Rust Version

* rustc 1.50.0 (cb75ad5db 2021-02-10)

### Affected Version of clap

* N/A

### Bug or Feature Request Summary

Cannot build on Windows

### Expected Behavior Summary

`cargo run` should work OR Readme should have an entry saying that this is an only *nix project

### Actual Behavior Summary

`cargo run` give a compile error

### Steps to Reproduce the issue

install rustup for windows and use 64 bit msvc version

**Comment by omarabid** [comment]
@gregorybleiker I'm aware of that but I don't have a Windows machine. You are welcome to investigate the issues and make a pull request.

**Comment by gregorybleiker** [comment]
That's ok. Just maybe add it to the readme?

**Comment by omarabid** [comment]
@gregorybleiker I'll work on making a list of compile target.

**Comment by bammi** [comment]
Readme still does not mention that it cant build on windows due to libsystemd
