### ISSUE TITLE
Problem compiling on MacOS

### ISSUE THREAD

**Issue by avi-cenna** [rust-starter/rust-starter#48]
First of all thanks for making this project. I think it's really cool. I ran into an issue building this and it seems that this package won't work on Mac. Would it be possible to make this dependency `slog-journald` (which relies on `libsystemd`) only for Linux?

```shell
   Compiling libsystemd v0.4.1
error[E0432]: unresolved import `nix::mqueue`
 --> /Users/navidbahmanyar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsystemd-0.4.1/src/activation.rs:2:10
  |
2 | use nix::mqueue::mq_getattr;
  |          ^^^^^^ could not find `mqueue` in `nix`

error[E0432]: unresolved import `nix::sys::memfd`
 --> /Users/navidbahmanyar/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsystemd-0.4.1/src/logging.rs:4:15
  |
4 | use nix::sys::memfd::memfd_create;
  |               ^^^^^ could not find `memfd` in `sys`

...
```

If this is a reasonable request, I wouldn't mind contributing a pull request for this.

**Comment by omarabid** [comment]
@avi-cenna Feel free to make a PR for this.

**Comment by omarabid** [comment]
@avi-cenna PR Merged. Re-open if the compilation to macOS still doesn't pass.
